title: Obscura Documentation
description: Documentation site for Obscura
remote_theme: just-the-docs/just-the-docs
color_scheme: dark
url: "https://docs.signalbyvre.com"
baseurl: ""

just_the_docs:
  custom_css:
    - custom.css
footer_content: "Obscura Documentation • Stage your persona. Own your privacy."

plugins:
  - jekyll-remote-theme
